<?php

namespace app\index\controller;

use think\Controller;

class Cross extends Controller
{
//    解决跨域
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin: *');
        header('Access-Control-Allow-Methods: POST,GET,PUT,OPTIONS,DELETE');//支持的http动作
        header('Access-Control-Allow-Headers: Origin,X-Requested-With,Content-Type,Accept,x-access-sign,x-access-time');
        if(request()->isOptions()){
            exit();
        }
    }
}